name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go build -o bin/godm-windows-amd64 ./cmd/godm/.
        name: Build Windows
        env:
          GOOS: windows
          GOARCH: amd64
      - run: go build -o bin/godm-linux-amd64 ./cmd/godm/.
        name: Build Linux
        env:
          GOOS: linux
          GOARCH: amd64
      - run: go build -o bin/godm-linux-arm64 ./cmd/godm/.
        name: Build Linux (Arm64)
        env:
          GOOS: linux
          GOARCH: arm64
      - run: go build -o bin/godm-darwin-amd64 ./cmd/godm/.
        name: Build MacOS (Amd64)
        env:
          GOOS: darwin
          GOARCH: amd64
      - run: go build -o bin/godm-darwin-arm64 ./cmd/godm/.
        name: Build MacOS (Arm64)
        env:
          GOOS: darwin
          GOARCH: arm64
      - uses: actions/upload-artifact@v4
        with:
          name: godm-${{ matrix.os }}
          path: ./bin
      - uses: softprops/action-gh-release@v2
        with:
          files: ./bin/*
          body: ${{ github.sha }}
          draft: false
          tag_name: PreReleaseCandidate
          prerelease: true
