name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: make build
      - uses: actions/upload-artifact@v4
        with:
          name: godm-${{ matrix.os }}
          path: ./bin
